[package]
name = "mica"
version = "0.0.0"
edition = "2024"

[dependencies]
rand = "0.9"
noise = "0.9"
pathfinding = "4.14"

# bevy
bevy = { version = "0.15" }

# plugins
ecs-tilemap = { package = "bevy_ecs_tilemap", version = "0.15" }
inspector-egui = { package = "bevy-inspector-egui", version = "0.29" }

[features]
debug = ["bevy/dynamic_linking"]

[profile.dev]
opt-level = 2

[profile.dev.package."*"]
opt-level = 3

[profile.release]
panic = 'abort'
strip = true
codegen-units = 1
lto = "fat"
